package main

import "leetcode/pkg/algorithm"

func main() {
	algorithm.Permute([]int{1, 2, 3})
	// algorithm.TrimMean([]int{6, 0, 7, 0, 7, 5, 7, 8, 3, 4, 0, 7, 8, 1, 6, 8, 1, 1, 2, 4, 8, 1, 9, 5, 4, 3, 8, 5, 10, 8, 6, 6, 1, 0, 6, 10, 8, 2, 3, 4})
	// algorithm.MaximumSwap(10) //10
	// algorithm.MaximumSwap(12) //1
	// algorithm.MaximumSwap(1993) //9913
	// algorithm.SpecialArray([]int{0, 4, 3, 0, 4})
	// algorithm.MincostToHireWorkers([]int{3, 1, 10, 10, 1}, []int{4, 8, 2, 2, 7}, 3) //30.66667
	// algorithm.MincostToHireWorkers([]int{10, 20, 5}, []int{70, 50, 30}, 2)
	// algorithm.PartitionString("gizfdfri") // 2
	// algorithm.MostFrequentEven([]int{29, 47, 21, 41, 13, 37, 25, 7})
	// algorithm.Jump([]int{2, 3, 1}) //1
	// algorithm.IsPalindrome("abcde")
	// algorithm.CountAndSay(5)
	// algorithm.UniqueLetterString("ABAB") // 12
	// algorithm.UniqueLetterString("ABA") // 8
	// algorithm.UniqueLetterString("A")
	// algorithm.UniqueLetterString("LEETCODE")
	// algorithm.UniqueLetterString("BBC")
	// algorithm.UniqueLetterString("leetcode")
	// algorithm.UniqueLetterString("ABC")
	// algorithm.UniqueLetterString("ABCD")
	// algorithm.UniqueLetterString("DELQGVWNZKIJJPSXOVWWIZUXCEGWSQLESNSRBMKZARFPAXSVWQEZDENDAHNNIBHGHTFDLPGDLFXMIYRFNLMXHNPIFUAXINXPXLCTTJNLGGMKJIOEWBECNOFQPVCIKIAZMNGHEHFMCPWSMJTMGVSXTOGCGUYKFMNCGLCBRAFJLJVPIVDOLJBURULPGXBVDCEWXXXLTRMSHPKSPFDGNVOCZWDXJUWVNAREDOKTZMIUDKDQWWWSAEUUDBHMWZELOSBIHMAYJEMGZPMDOOGSCKLVHTGMETHUISCLJKDOQEWGVBULEMUXGTRKGXYFDIZTZWMLOFTCANBGUARNWQEQWGMIKMORVQUZANJNRNPMJWYLVHWKDFLDDBBMILAKGFROEQAMEVONUVHOHGPKLBPNYZFPLXNBCIFENCGIMIDCXIIQJWPVVCOCJTSKSHVMQJNLHSQTEZQTTMOXUSKBMUJEJDBJQNXECJGSZUDENJCPTTSREKHPRIISXMWBUGMTOVOTRKQCFSDOTEFPSVQINYLHXYVZTVAMWGPNKIDLOPGAMWSKDXEPLPPTKUHEKBQAWEBMORRZHBLOGIYLTPMUVBPGOOOIEBJEGTKQKOUURHSEJCMWMGHXYIAOGKJXFAMRLGTPNSLERNOHSDFSSFASUJTFHBDMGBQOKZRBRAZEQQVWFRNUNHBGKRFNBETEDJIWCTUBJDPFRRVNZENGRANELPHSDJLKVHWXAXUTMPWHUQPLTLYQAATEFXHZARFAUDLIUDEHEGGNIYICVARQNRJJKQSLXKZZTFPVJMOXADCIGKUXCVMLPFJGVXMMBEKQXFNXNUWOHCSZSEZWZHDCXPGLROYPMUOBDFLQMTTERGSSGVGOURDWDSEXONCKWHDUOVDHDESNINELLCTURJHGCJWVIPNSISHRWTFSFNRAHJAJNNXKKEMESDWGIYIQQRLUUADAXOUEYURQRVZBCSHXXFLYWFHDZKPHAGYOCTYGZNPALAUZSTOU") //629134
}
